### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by maxerbubba** [AmberEngine/stepfunctions_activity_worker#10]
print("♡")

This line throws an exception in my terminal when redirecting to an output file.  please remove, or use ```logging.debug("Heartbeat.")``` instead.

Example:
```python demo.py 2>&1 > output.txt```

Output:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/maxreede/brazil-pkg-cache/packages/CPython36Runtime/CPython36Runtime-release.269427.0/AL2012/DEV.STD.PTHREAD/build/python3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/amazon/lib/python3.6/site-packages/stepfunctions_activity_worker/heartbeat.py", line 20, in run
    print("\u2661")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2661' in position 0: ordinal not in range(128)
```

**Comment by MaxwellGBrown** [comment]
Can't recreate the unicode => ascii encoding error, and at first glance not sure what would be trying to encode the heart icon into ascii.

We're certainly capable of changing the heart character, but I would prefer to address making sure what we have currently is compatible with more environments.

I see you're using 3.6, which afaik shouldn't have issues with the Unicode character. Can you share any more details about your set up?

**Comment by maxerbubba** [comment]
I think it may be due to https://github.com/Microsoft/vscode/issues/6269

I am using VSCode on an old linux distribution, to ssh into a machine that then runs a docker image of amazonlinux.  I tried to repro on Windows by launching an amazonlinux docker image from within VSCode, and it worked fine.

Thanks for looking
